module.exports = {
  apps: [
    {
      name: 'cmms-api',
      script: 'src/api/server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 3000,
      out_file: 'logs/api.out.log',
      error_file: 'logs/api.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'cmms-normalizer',
      script: 'src/consumers/consumer1-normalizer.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 5000,
      out_file: 'logs/normalizer.out.log',
      error_file: 'logs/normalizer.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'cmms-aggregator',
      script: 'src/consumers/consumer2-aggregator.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 5000,
      out_file: 'logs/aggregator.out.log',
      error_file: 'logs/aggregator.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'cmms-anomaly',
      script: 'src/consumers/consumer3-anomaly.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      restart_delay: 5000,
      out_file: 'logs/anomaly.out.log',
      error_file: 'logs/anomaly.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'cmms-producer',
      script: 'src/ingestion/coinbaseProducer.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      restart_delay: 5000,
      out_file: 'logs/producer.out.log',
      error_file: 'logs/producer.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
